version: "3.7"

services:
  entrypoint:
    image: registry.ops.katiecordescodes.com/personalsite-externals-entrypoint
    labels:
      - "traefik.enable=false"
    ports:
      - "3000:8080"

  app:
    image: registry.ops.katiecordescodes.com/personalsite-externals-app
    labels:
      - "traefik.enable=false"
    build:
      context: .
      dockerfile: .docker/app.dockerfile
      args:
        PHPTYPE: fpm
      target: prod
    volumes:
      - ./.env:/var/www/.env