version: "3.7"

# Required environment variables:
# - TRAEFIK_IDENTIFIER
# - SITE_URL
# - UID
# - GID

services:
  entrypoint:
    image: registry.ops.katiecordescodes.com/personalsite-externals-entrypoint
    build:
      context: .
      dockerfile: .docker/entrypoint.dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_IDENTIFIER}.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.${TRAEFIK_IDENTIFIER}.entryPoints=web"
      - "traefik.http.routers.${TRAEFIK_IDENTIFIER}.service=${TRAEFIK_IDENTIFIER}"
      - "traefik.http.services.${TRAEFIK_IDENTIFIER}.loadbalancer.server.port=8080"
    networks:
      - default
      - traefik

  app:
    image: registry.ops.katiecordescodes.com/personalsite-externals-app
    build:
      context: .
      dockerfile: .docker/app.dockerfile
      args:
        PHPTYPE: fpm
        UID: $UID
        GID: $GID
    user: "$UID:$GID"
    labels:
      - "traefik.enable=false"
    networks:
      - default

networks:
  traefik:
    external: true